### ISSUE TITLE
(K32)GetModuleBaseNameW: win32 error: failed to resolve the file name of the target process

### ISSUE THREAD

**Issue by netcorefan1** [Broihon/GH-Injector-Library#10]
Hello,
using GH Library I would like to launch a process in a suspended state (probably using CreateProcess since I believe that should be the only one to provide this functionality), enable an hook and then resume the process. In the other issue you said me that this is only possible with NtCreateThreadEx which is the one I use by default (and If I am not wrong the recommended one). 

This is how I do the injection:
```
var siex = new Kernel32.STARTUPINFOEX();
CreateProcess(targetExe, null, null, null, false, CREATE_PROCESS.CREATE_SUSPENDED, null, null, siex, out var notepad));

var id = new Native.InjectiondataW
{
    szDllPath = dllToInject,
    ProcessID = notepad.dwProcessId,
    Mode = LoadLibraryExW,
    Method = NtCreateThreadEx,
    GenerateErrorLog = false
};
InjectW(ref id)
```
It continue until the attachment to the process and then:
**K32GetModuleBaseNameW failed: 00000006**
```
Error code: InjErrCantGetExeFilename
(K32)GetModuleBaseNameW: win32 error: failed to resolve the file name of the target process
The handle is invalid.
```
Tried with all the injection modes available, but same error.

Then I decided to go deeper and discovered that here is the call function that failed:

<img width="627" alt="2021-02-10-02-39-15" src="https://user-images.githubusercontent.com/63934725/107452356-52bf8580-6b49-11eb-98a1-0a0a88861cca.png">

Basically GetModuleBaseNameW fails to resolve the executable name and stop execution. On non suspended process it works.
I suspect that it fails because on a suspended process only NTDLL is the one working while GetModuleBaseNameW  should belong to Kernel32. May there are alternative function available in NTDLL that could do the same.

Anyway, I commented that code and manually added the already known executable name with the following code:

<img width="678" alt="2021-02-10-02-46-07" src="https://user-images.githubusercontent.com/63934725/107452817-307a3780-6b4a-11eb-8ac1-765360a4f5ed.png">

As a result of this change the execution continued and completed with success.
Surprisingly I was also able to enter into the injected dll and resume the process.

So, is really necessary that call at GetModuleBaseNameW ??? I see that it fills `InjectiondataW->szTargetProcessExeFileName`.
If you need to know the exe file name the user can just fill that field them self and we are good to go. It would be fine if you could implement such functionality in your lib and if you need I could provide some working code to simplify the process. A function like `CreateAndInject(bool suspended)`.

I really like this lib, it's the only one that works, there are little things to improve and fix, but is still amazing!

**Comment by Broihon** [comment]
I never intended this library to inject into a suspended process so it's not a bug in my opinion. Additionally this is caused by the insane lack of documentation of the used API.

The executable name is only used for the debug output and not critical for the injection process but my train of thought was if the injector isn't even able to grab a module name then the injection would most certainly not work anyway. And I still consider this a logical assumption to make but again, logic doesn't work when you deal with Windows.

I did some research on why this fails and it's honestly insane. It's not which dll the function belongs to and obviously there is absolutely no documentation on this. It turns out that PEB::Ldr is a nullptr when the process gets created in a suspended state.
All the modules are already loaded but the pointer to the PEB_LDR_DATA is just 0. Why? No clue. Does it make any sense? No. Is it mentioned anywhere? No.
Anyway, switching to an API that queries kernel data will do the trick.

**Comment by netcorefan1** [comment]
Sorry for reopening this, but I wanted to thank you for the time you have taken to investigate and to confirm that your fix worked. QueryFullProcessImageName works along with the resuming process. Do you will apply this fix in the next release?
Although injecting into a suspended process was not on the scope of the library, if I am not wrong by using NtCreateThreadEx  everything was already in your hands (unless there are other bad surprises to expect I would say that injecting a dll in a suspended notepad process and resume it from inside the injected dll is a great result. This will open to the possibility to deal with detection mechanism and hooking all the API calls a process can do before it starts. I would say it adds a great value to your injector.

> The executable name is only used for the debug output and not critical for the injection process but my train of thought was if the injector isn't even able to grab a module name then the injection would most certainly not work anyway. And I still consider this a logical assumption to make but again, logic doesn't work when you deal with Windows.

Even if it is not critical to the injection process your logical assumption for me it is enough to take care about this and in order to be bring an extra level of safety after this fix I need to make you to quick questions:
- After the fix I experienced for the first time several times injection timeout and honestly I can't imagine how that function replacement can even have some sort on influence. I will investigate to see what could be the cause. There is a Timeout field in the Injection struct, you think can help with this? 
- To resume the thread I just call `ResumeThread(hThread);` but I saw from other libraries they do that way:
```
if((hThread = OpenThread(THREAD_SUSPEND_RESUME, FALSE, ThreadID)) == NULL)
        THROW(STATUS_INTERNAL_ERROR, L"Unable to open wake up thread.");

    if(!ResumeThread(hThread))
        THROW(STATUS_INTERNAL_ERROR, L"Unable to resume process main thread.");
```
What could be the correct way?
