### ISSUE TITLE
Cannot find the function GetImportState

### ISSUE THREAD

**Issue by BoliLi** [Broihon/GH-Injector-Library#14]
Hi, 

My test failed at finding function GetImportState. But ok with InjectA and GetSymbolState. Can somebody help?

auto InjectA = (f_InjectA)GetProcAddress(hInjectionMod, "InjectA");
if (InjectA == nullptr)
{
	printf("[x] Cannot find the function InjectA!\n");
	return -1;
}
auto GetSymbolState = (f_GetSymbolState)GetProcAddress(hInjectionMod, "GetSymbolState");
if (GetSymbolState == nullptr)
{
	printf("[x] Cannot find the function GetSymbolState!\n");
	return -1;
}
auto GetImportState = (f_GetImportState)GetProcAddress(hInjectionMod, "GetImportState");
if (GetImportState == nullptr)
{
	printf("[x] Cannot find the function GetImportState!\n");
	return -1;
}

**Comment by Broihon** [comment]
Did you build the current version or download one of the release versions?
The GetImportState function is not implemented in the current releases.

**Comment by Broihon** [comment]
GetImportState is now implemented in the current release.
