### ISSUE TITLE
Can't get the DLL's path after manual map injection w/ erase PE

### ISSUE THREAD

**Issue by 0x597575746F** [Broihon/GH-Injector-Library#17]
Is there anyway to get the DLL's name and path when using manual map injection and erase PE? 

I understand that its by design so that it could hide the DLL, but maybe there are other methods to find it?

I'm using V4.4 and used the Kernel32's GetModuleFileName, with the DllMain's first argument as the hmodule and got an empty string as result.

**Comment by Broihon** [comment]
Not possible. The mapped dll is not linked to the PEB and no file mapping exists. Thus it's not possible for any API to resolve the file path.
