### ISSUE TITLE
Download/import failure. Error code: 0x0000003d

### ISSUE THREAD

**Issue by leo4048111** [Broihon/GH-Injector-Library#19]
This happens when i'm running the injector.

**The injector requires PDB files for the ntdll.dll to work.
These files will be downloaded from the Microsoft Symbol Server
and will take up about 5MB.
Do you want to download the files now?**
--> Clicked Yes
**Download/import failure. Error code: 0x0000003d
The injector cannot function without the PDB files.
Please restart the injector.**

**Debug log:**
Injection module loaded at 00007FFB385B0000
Set print callback: 00007FF7F76B2700
Creating DragDrop window
 HWND = 00070106
 Loading settings
Don't update check
 Settings loaded successfully
Tooltips enabled
GH Injector V4.5
Initializing GUI
GUI initialized
Old index = -1
Dock = 0
  SYMBOL_PARSER: RVA 00016A10 -> LdrLoadDll
  SYMBOL_PARSER: RVA 0000FBF0 -> LdrUnloadDll
  SYMBOL_PARSER: RVA 0001733C -> LdrpLoadDll
  SYMBOL_PARSER: RVA 000168A0 -> LdrGetDllHandleEx
  SYMBOL_PARSER: RVA 00081AD0 -> LdrGetProcedureAddress
  SYMBOL_PARSER: RVA 0009D130 -> NtQueryInformationProcess
  SYMBOL_PARSER: RVA 0009D4D0 -> NtQuerySystemInformation
  SYMBOL_PARSER: RVA 0009D2B0 -> NtQueryInformationThread
  SYMBOL_PARSER: RVA 000A3C00 -> memmove
  SYMBOL_PARSER: RVA 00087D00 -> RtlZeroMemory
  SYMBOL_PARSER: RVA 0002A9A0 -> RtlAllocateHeap
  SYMBOL_PARSER: RVA 00024760 -> RtlFreeHeap
  SYMBOL_PARSER: RVA 00019580 -> RtlAnsiStringToUnicodeString
  SYMBOL_PARSER: RVA 0009D470 -> NtOpenFile
  SYMBOL_PARSER: RVA 0009CED0 -> NtReadFile
  SYMBOL_PARSER: RVA 0009D2F0 -> NtSetInformationFile
  SYMBOL_PARSER: RVA 0009D030 -> NtQueryInformationFile
  SYMBOL_PARSER: RVA 0009CFF0 -> NtClose
  SYMBOL_PARSER: RVA 0009D110 -> NtAllocateVirtualMemory
  SYMBOL_PARSER: RVA 0009D1D0 -> NtFreeVirtualMemory
  SYMBOL_PARSER: RVA 0009D810 -> NtProtectVirtualMemory
  SYMBOL_PARSER: RVA 0009D750 -> NtCreateSection
  SYMBOL_PARSER: RVA 0009D310 -> NtMapViewOfSection
  SYMBOL_PARSER: RVA 0009E620 -> NtCreateThreadEx
  SYMBOL_PARSER: RVA 000DC010 -> RtlQueueApcWow64Thread
  SYMBOL_PARSER: RVA 000108F0 -> RtlInsertInvertedFunctionTable
  SYMBOL_PARSER: RVA 00047C14 -> LdrpHandleTlsData
  SYMBOL_PARSER: RVA 0007D040 -> LdrLockLoaderLock
  SYMBOL_PARSER: RVA 0007DEB0 -> LdrUnlockLoaderLock
  SYMBOL_PARSER: RVA 00081680 -> RtlAddVectoredExceptionHandler
  SYMBOL_PARSER: RVA 00082080 -> RtlRemoveVectoredExceptionHandler
  SYMBOL_PARSER: RVA 0009D490 -> NtDelayExecution
  SYMBOL_PARSER: RVA 0016A520 -> LdrpHeap
  SYMBOL_PARSER: RVA 0017F500 -> LdrpInvertedFunctionTable
  SYMBOL_PARSER: RVA 0017F3E8 -> LdrpVectorHandlerList
  SYMBOL_PARSER: RVA 00164520 -> LdrpTlsList
  SYMBOL_PARSER: RVA 0002A0A0 -> RtlRbRemoveNode
  SYMBOL_PARSER: RVA 0016B468 -> LdrpModuleBaseAddressIndex
  SYMBOL_PARSER: RVA 0016B478 -> LdrpMappingInfoIndex
  SYMBOL_PARSER: RVA 00012224 -> LdrProtectMrdata
  SYMBOL_PARSER: RVA 0001A360 -> LdrpPreprocessDllName
  SYMBOL_PARSER: RVA 0001FA14 -> LdrpLoadDllInternal
  SYMBOL_PARSER: RVA 00067AC0 -> RtlAddFunctionTable
 SYMBOL_LOADER::Cleanup
 Native ntdll symbols loaded
All symbols loaded
Import handler (wow64) failed: 0000003D
All symbols loaded
Import handler (wow64) failed: 0000003D
All symbols loaded
Import handler (wow64) failed: 0000003D
Processlist updated
Processlist updated
Beginning download(s)
All symbols loaded
All symbols loaded
Import handler (wow64) failed: 0000003D
Import handler (wow64) failed: 0000003D

built with qt5.15.2 + msvc v143 vs2022
running on win11 build 22000.527.0

**Comment by Broihon** [comment]
You need to include the x86 build of the library in the same directory as it is needed for wow64 symbol loading.
