### ISSUE TITLE
Error 0x0000001C

### ISSUE THREAD

**Issue by mavetek** [Broihon/GH-Injector-Library#2]
The library builds fine but when I try to use it I get the error 0x0000001C
If I use the already built dll works fine. Maybe there is some configuration missing in Visual Studio?

Version            : GH Injector V3.4
OS                 : Windows 10 Enterprise 2004 (Build 19035)
File               : (nullptr)
Target             : (undetermined)
Target PID         : 31360
Source             : Injection.cppr.cpp in InjectWImports at line 116
Errorcode          : 0x0000001C
Advanced errorcode : 0x00000000
Injectionmode      : LoadLibraryExW
Launchmethod       : NtCreateThreadEx
Platform           : ---
HandleValue        : 0x00000000
Flags              : 0x00000000

**Comment by Broihon** [comment]
This error occurs when downloading the pdbs isn't done yet.
The first time you run the injector the DllMain will launch threads to download the ntdll pdbs which obviously can take a couple of seconds. 
Just load the dll, then wait a few seconds. Maybe just check manually if the pdbs were downloaded. The files are being downloaded in Symbol Parser.cpp#313.
After that's done the error should be gone.

**Comment by mavetek** [comment]
Yup, I just had to wait for the pdb. Thank you.
