### ISSUE TITLE
injection keep failing 

### ISSUE THREAD

**Issue by badewen** [Broihon/GH-Injector-Library#20]
log file :

06-03-2022 16:39:18
Version            : GH Injector V4.6
OS                 : Windows 10 21H2 (Build 19044)
File               : D:\visual studio project\c++ dll internal chit\asd.dll
Target             : ac_client.exe
Target PID         : 12404
Source             : NtCreateThreadEx WOW64.cpp in SR_NtCreateThreadEx_WOW64 at line 251
Errorcode          : 0x10100009
Advanced errorcode : 0x00000102
Injectionmode      : LoadLibraryExW
Launchmethod       : NtCreateThreadEx
Platform           : wow64
HandleValue        : 0x00000000
Flags              : 0x00000000

debug console:

Injection module loaded at 00007FFD0BBC0000
Set print callback: 00007FF785CD2740
Creating DragDrop window
 HWND = 000A06F0
 Loading settings
Added file: D:/visual studio project/c++ dll internal chit/asd.dll
 Settings loaded successfully
Tooltips enabled
GH Injector V4.6
Initializing GUI
GUI initialized
Console docked: right
Injector ready
Processlist updated
Launching injection thread
All symbols loaded
Import handler finished
All symbols loaded
Import handler finished
All symbols loaded
Import handler finished
All symbols loaded
Import handler finished
InjectW called with pData = 0000002C06F3A180
Attached to target process
Target process name = ac_client.exe
Validating specified file
File validated and prepared for injection:
 D:\visual studio project\c++ dll internal chit\asd.dll
 Begin InjectDLL_WOW64
 Shell data initialized
  Shellsize	= 000005D0
  Total size	= 000009A8
  pArg        = 00640000
  pShell      = 006403D0
 Shell written to memory
 Entering StartRoutine_WOW64
  Begin SR_NtCreateThreadEx_WOW64
   Creating ProcessInfo
   ProcessInfo initialized
  Codecave allocated at 0000000000650000
  Creating thread with:
   pRoutine = 00650018
   pArg     = 00650000
  Thread created with TID = 002710 (010000)
  Entering wait state
  WaitForSingleObject failed: 00000102
 Return from StartRoutine_WOW64
 StartRoutine_WOW64 failed: 10100009
Injection finished
Injection thread returned
Check the error log for more information
Injection 1/1 finished
Injection (1/1) failed:
  Error = 10100009

if this issue is dumb, im sorry

**Comment by badewen** [comment]
should this issue be in the gui repos?

**Comment by badewen** [comment]
nvm it worked smh like magic

**Comment by Broihon** [comment]
This is the correct repo. Error 0x00000102 means WaitForSingleObject timed out waiting for the thread to execute. Unless the target process crashed this usually is caused by a deadlocked DllMain.
Do you know what you changed to make it work? Maybe debug vs. release build?

**Comment by badewen** [comment]
i changed the injection method
