### ISSUE TITLE
Won't run on Windows 11

### ISSUE THREAD

**Issue by illumen** [Broihon/GH-Injector-Library#22]
Hey,

I can't seem to start this application on Windows 11.

Info:
_OS_: Windows 11 Pro
_Version_: 21H2
_Build_: 22000.588

When I try to run the application, nothing happens and I don't get any error messages (not in Event Viewer aswell).

Any suggestions?

**Comment by Broihon** [comment]
Windows Defender probably being dumb. How did you solve the problem?

**Comment by illumen** [comment]
I was stupid, I cloned the GUI library and compiled it as well, works fine now, I didn't realize the GUI was in a separate repo!
