### ISSUE TITLE
Feature Request, Manual Map from file in memory

### ISSUE THREAD

**Issue by WheresRushia** [Broihon/GH-Injector-Library#25]
I don't know how to ask for a request here at github so I'm putting it as an issue. Can we manual map from a file in memory, like a file downloaded with libcurl? I tried to read your code but it's kinda complicated so I was never able to implement it, but maybe you can....

**Comment by Broihon** [comment]
You'd have to patch the file validation checks, copy the raw DLL into the target process and adjust the mapping shell code.
I'll take this into consideration, I'm currently working on a quite complex update though so it probably will take some more time before this will be implemented.

**Comment by YeFell** [comment]
I need to implement SEH support myself, what should I do.

**Comment by Broihon** [comment]
> I need to implement SEH support myself, what should I do.

See https://github.com/Broihon/GH-Injector-Library/blob/master/GH%20Injector%20Library/Manual%20Mapping.cpp#L1610
Not sure what you mean or how it's related to this issue.

**Comment by YeFell** [comment]
Thank,

**Comment by X3P0** [comment]
> You'd have to patch the file validation checks, copy the raw DLL into the target process and adjust the mapping shell code. I'll take this into consideration, I'm currently working on a quite complex update though so it probably will take some more time before this will be implemented.

Any progress on this?

Or have any idea what parts of the shell code need changing I'd like to implement this myself

**Comment by Broihon** [comment]
As 0xSomething said. I've already implemented this and it will be officially supported in the next update. Since I'm working on other features it'll still take some time until the update comes out.

**Comment by Broihon** [comment]
Implemented. See [Memory_Inject](https://github.com/Broihon/GH-Injector-Library/blob/master/GH%20Injector%20Library/Injection.h#L96).
