### ISSUE TITLE
My injector closes when I finish injecting.

### ISSUE THREAD

**Issue by DestroyerDarkNess** [Broihon/GH-Injector-Library#29]
Hello, First I must say: Great Library, what I like the most is how stable it is.

I made my Own Wrapper for .NET. I am trying all the methods with different flags. and it works perfectly.

But the Problem is that When I finish Injecting, my application (Injector) closes. and it does not generate the .log either .

I really have no idea what is going on. I don't have any specific details. any ideas?

**Comment by Broihon** [comment]
Could be an internal crash. I need more specifics to find out what's going on here. Does the injection succeed? Does this happen with all methods or only specific ones? Are you using handle hijacking?

**Comment by DestroyerDarkNess** [comment]
This is a code sample of what I'm doing:

`
extern "C" __declspec(dllexport)  DWORD Inject(DWORD TargetProcessId, char* DllPathToInject)
{
 
auto InjectA = (f_InjectA)GetProcAddress(hInjectionMod, "InjectA");
   
INJECTION_MODE InjMode = INJECTION_MODE::IM_LoadLibraryExW; 

LAUNCH_METHOD LachMode = LAUNCH_METHOD::LM_NtCreateThreadEx; 

INJECTIONDATAA data =
{
	"",
	TargetProcessId,
	InjMode,
	LachMode,
	NULL,
	0,
	NULL,
	NULL,
	true
};

strcpy(data.szDllPath, DllPathToInject);

return InjectA(&data);

}
`

I have used all the flags, but still, it closes after Inject.

Inject perfectly. but I don't understand why it closes.

**Comment by DestroyerDarkNess** [comment]
I close the topic.

**Comment by MlSAKA-MlKOTO** [comment]
Sorry but how to find correct "Flags"? I'm new to dll injection and don't know what it means qAq
