### ISSUE TITLE
Shell failed with 0x0040000A

### ISSUE THREAD

**Issue by MrKinauJr** [Broihon/GH-Injector-Library#30]
Heyo, just tried injecting and it just said Shell failed with 0040000A.
I have no idea, what that could mean tbh, in the code it said not being able to get some import. But it was an internal error afaik.
I would greatly appreciate the help.

For the DLL I injected, it's a basic 64bit DLL with the default Settings for a DLL in VS.
Only thing i "imported" is D3D9 for an Overlay.
I used the Manual Mapping Method.

**Comment by GH-Rake** [comment]
Show us your DllMain()

**Comment by Broihon** [comment]
As Rake already said there should be an error log with an extended error code. Are you using a debug mode build by any chance?

**Comment by MrKinauJr** [comment]
Yes, I do use debug mode. That might make sense, I'll try using the Release Mode.
And I'll try to get the debug log, as it does not happen on my PC I need to wait for a Mate to inject it.

`cpp
BOOL APIENTRY DllMain( HMODULE hModule,
                       DWORD  ul_reason_for_call,
                       LPVOID lpReserved
)
{
    switch (ul_reason_for_call)
    {
    case DLL_PROCESS_ATTACH:
        g_hModule = hModule;
        CreateThread(NULL, NULL, (LPTHREAD_START_ROUTINE)main, NULL, NULL, NULL);
    case DLL_THREAD_ATTACH:
    case DLL_THREAD_DETACH:
    case DLL_PROCESS_DETACH:
        break;
    }
    return TRUE;
}
`
