### ISSUE TITLE
GetDownloadProgress Doesn't work correctly...

### ISSUE THREAD

**Issue by DestroyerDarkNess** [Broihon/GH-Injector-Library#31]
I tried to access it through my wrapper. 

The float type in vb would be single. however it still doesn't work.

Couldn't you change the return to an integer?

such as GetSymbolState and GetImportState work fine.

**Comment by Broihon** [comment]
I won't change the function to an integer since a floating point value makes significantly more sense because it provides more precise information. 
It however should be possible to use it in VB regardless. How are you declaring the function prototype?

**Comment by Broihon** [comment]
Closing this since it's not an issue.

**Comment by DestroyerDarkNess** [comment]
Hello, try to do it from C ++ and it doesn't work.

` auto GetDownloadProgress 	= (f_GetDownloadProgress)GetProcAddress(hInjectionMod, "GetDownloadProgress");`

This is what I am using to get the progress of the download, I obviously call **"StartDownload"**. But a large negative number returns to me. In the end I have to trust is **GetSymbolState** and **GetImportState** to know that the download end.

-----------------------------------------------------------------------------------

By the way in the Header of Injection, which I place as an example, you put as a comment:

`
auto GetDownloadProgress 	= (f_GetDownloadProgress)GetProcAddress(hInjectionMod, "GetDownloadProgress");
`

But you declare this:

`
using f_GetDownloadProgressEx = float(__stdcall *)(int index, bool bWow64);
`

Should there be something like this? :

`
typedef float(*f_GetDownloadProgress);
`

I don't know if I'm wrong. But what is and how it is used: **f_GetDownloadProgressEx** ??

**Comment by Broihon** [comment]
Forgot to remove the old function prototype from the header. GetDownloadProgress is deprecated (though still works). Instead use GetDownloadProgressEx (see updated ReadMe).
GetSymbolState and GetImportState will only return successfully after the download is finished. There's no need to check the download progress to verify if everything's ready. All the required prototypes are defined in Injection.h. You don't have to manually declare any prototypes (unless you want to use the deprecated GetDownloadProgress function).

**Comment by DestroyerDarkNess** [comment]
Thank you for responding as fast Bro, as always thanks for this great library.

**Comment by DestroyerDarkNess** [comment]
Hello, Sorry to re-open again. I have a question and I don't know if the error is on me;

When I am downloading the symbols in **x64 mode**, **GetImportState**, it stays in an eternal loop with a value of **71**. Instead with **x86** the value if it changes to **0**. 

**(This only happened when the symbols are downloaded)**

![UnFix](https://user-images.githubusercontent.com/32405118/210025385-b83e1d45-955c-4ff9-b611-16d8e4d8a17b.png)

**Any ideas ?**

**Comment by Broihon** [comment]
All the error codes are defined in Error.h. Error code 0x47 means that you're missing "GH Injector SM - x86.exe".

**Comment by DestroyerDarkNess** [comment]
Now it works, thanks. :)
