### ISSUE TITLE
Manual map injection keep failing

### ISSUE THREAD

**Issue by your-n1ghtmare** [Broihon/GH-Injector-Library#32]
**Hi** I have a problem with injection of dll

**Log file:**
03-01-2023 16:10:26
Version            : GH Injector V4.7
OS                 : Windows 10 22H2 (Build 19045)
File               : hello_world86.dll
Target             : x86process.exe
Target PID         : 7360
Source             : Manual Mapping.cpp in MMAP_NATIVE::ManualMap at line 291
Errorcode          : 0x00400002
Advanced errorcode : 0xC0000034
Injectionmode      : ManualMap
Launchmethod       : NtCreateThreadEx
Platform           : x64/x86 (native)
HandleValue        : 0x00000000
Flags              : 0x00FE0000

**Code:**
```
int main() {

	HINSTANCE hInjectionMod = LoadLibrary(GH_INJ_MOD_NAME);

	auto InjectA = (f_InjectA)GetProcAddress(hInjectionMod, "InjectA");
	auto GetSymbolState = (f_GetSymbolState)GetProcAddress(hInjectionMod, "GetSymbolState");
	auto GetImportState = (f_GetSymbolState)GetProcAddress(hInjectionMod, "GetImportState");
	auto StartDownload = (f_StartDownload)GetProcAddress(hInjectionMod, "StartDownload");
	auto GetDownloadProgressEx = (f_GetDownloadProgressEx)GetProcAddress(hInjectionMod, "GetDownloadProgressEx");

	Sleep(500);
	StartDownload();

	while (GetDownloadProgressEx(PDB_DOWNLOAD_INDEX_NTDLL, false) != 1.0f)
	{
		Sleep(10);
	}

	while (GetSymbolState() != 0)
	{
		Sleep(10);
	}

	while (GetImportState() != 0)
	{
		Sleep(10);
	}

	DWORD TargetProcessId = FindProcessId("x86process.exe");
	DWORD flags = MM_DEFAULT;

	INJECTIONDATAA data =
	{
		"",
		TargetProcessId,
		INJECTION_MODE::IM_ManualMap,
		LAUNCH_METHOD::LM_NtCreateThreadEx,
		flags,
		2000,
		NULL,
		NULL,
		true
	};

	strcpy(data.szDllPath, "hello_world86.dll");
	InjectA(&data);

	return 0;
}
```

**Comment by Broihon** [comment]
You need to copy the full path to the file into the data structure and not just the filename.

**Comment by your-n1ghtmare** [comment]
It doesn't help. I copied the full path to dll. It feels like Manual map doesn't work at all. I tried to set various flags and launch method's, but besides IM_LoadLibraryExW, LM_NtCreateThreadEx with zero flags does not work.
I use a dll and a 32 bit process for injection

**Comment by Broihon** [comment]
There's not much to go off here. Does V4.8 fix the problem? If not please reopen the issue.
