### ISSUE TITLE
Don't know how to make it run

### ISSUE THREAD

**Issue by MlSAKA-MlKOTO** [Broihon/GH-Injector-Library#34]
I just tried to run the example in Readme. I added a "main" function to make it compilable. But it reports error when going to main function with the error code "0xC0000005". I didn't arrange anything else except adding main() arranged the "data" and deteled the strcpy function;

**Comment by Broihon** [comment]
Post the code.

**Comment by MlSAKA-MlKOTO** [comment]
SURE
`#include "Injection.h"

int main() {

	HINSTANCE hInjectionMod = LoadLibrary(GH_INJ_MOD_NAME);

	auto InjectA = (f_InjectA)GetProcAddress(hInjectionMod, "InjectA");
	auto GetSymbolState = (f_GetSymbolState)GetProcAddress(hInjectionMod, "GetSymbolState");
	auto GetImportState = (f_GetSymbolState)GetProcAddress(hInjectionMod, "GetImportState");
	auto StartDownload = (f_StartDownload)GetProcAddress(hInjectionMod, "StartDownload");
	auto GetDownloadProgressEx = (f_GetDownloadProgressEx)GetProcAddress(hInjectionMod, "GetDownloadProgressEx");

	Sleep(500);
	StartDownload();

	while (GetDownloadProgressEx(PDB_DOWNLOAD_INDEX_NTDLL, false) != 1.0f)
	{
		Sleep(10);
	}

	while (GetSymbolState() != 0)
	{
		Sleep(10);
	}

	while (GetImportState() != 0)
	{
		Sleep(10);
	}

	DWORD TargetProcessId = 1956;//FindProcessId("x86process.exe");
	DWORD flags = MM_DEFAULT;

	INJECTIONDATAA data =
	{
		"",
		TargetProcessId,
		INJECTION_MODE::IM_ManualMap,
		LAUNCH_METHOD::LM_NtCreateThreadEx,
		flags,
		2000,
		NULL,
		NULL,
		true
	};

	strcpy(data.szDllPath, "C:\\Users\\CHUAN\\source\\repos\\WarHook-main\\x64\\Debug\\Warhook.dll");
	InjectA(&data);

	return 0;
}`

**Comment by MlSAKA-MlKOTO** [comment]
> Post the code.

sorry it's my fault. I forget to add the dll and lib sources.
btw, now it could download normally, while it gaves the error code "00000047". What could I do to deal with that?

**Comment by Broihon** [comment]
The error codes you provided sadly only indicate that the target process has crashed.
The problem most likely is that you set the timeout value to 0ms.
