### ISSUE TITLE
Error!

### ISSUE THREAD

**Issue by Sobhy92** [Broihon/GH-Injector-Library#36]
does Hijack handle need more work because it's not working?

**Comment by Sobhy92** [comment]
my code:

#define _CRT_SECURE_NO_WARNINGS

#include "Injection.h"

HINSTANCE hInjectionMod = LoadLibrary(GH_INJ_MOD_NAME);
	
auto InjectA = (f_InjectA)GetProcAddress(hInjectionMod, "InjectA");
auto GetSymbolState = (f_GetSymbolState)GetProcAddress(hInjectionMod, "GetSymbolState");
auto GetImportState = (f_GetSymbolState)GetProcAddress(hInjectionMod, "GetImportState");
auto StartDownload = (f_StartDownload)GetProcAddress(hInjectionMod, "StartDownload");
auto GetDownloadProgressEx = (f_GetDownloadProgressEx)GetProcAddress(hInjectionMod, "GetDownloadProgressEx");


int main() {



	StartDownload();

	
	DWORD TargetProcessId = 3184;
	const char* DllPathToInject = "C:\\flash.dll";
	INJECTIONDATAA data =
	{
		"",
		TargetProcessId,
		INJECTION_MODE::IM_LoadLibraryExW,
		LAUNCH_METHOD::LM_QueueUserAPC,
		INJ_HIJACK_HANDLE,
		0,
		NULL,
		NULL,
		true
	};

	strcpy(data.szDllPath, DllPathToInject);

	InjectA(&data);

}

**Comment by Broihon** [comment]
What error code are you getting? Keep in mind to:
1) run as administrator 
2) to hijack a handle the native version of the injector has to be used (so most likely the x64 version) 
3) there might not actually be a compatible handle

**Comment by Sobhy92** [comment]
Failed to grab handle list: C0000004
    201809 handles found
  3417 process handles found
  0 handle(s) to target process found
 No compatible handle found
 
 but injection works with your qt injector

**Comment by Broihon** [comment]
By default the injection library doesn't enable SeDebugPrivilege - the Qt GUI however does. In hindsight that's kinda stupid of me.
Without SeDebugPrivilege enabled you can't attach to system processes like lsass or csrss. Try to manually enable the privilege for your process.

Another - unrelated - thing I noticed is that you set the timeout value to 0 in the initialization of the INJECTIONDATAA structure. You have to increase that you at least a couple of ms when doing any injection but specifically handle hijacking.

**Comment by Sobhy92** [comment]
ok thanks.
