### ISSUE TITLE
Unable to inject the dll

### ISSUE THREAD

**Issue by nafalabi** [Broihon/GH-Injector-Library#7]
Hi,

I can't seem to successfully inject my dll

the error I got from `GH_Inj_Log.txt` 

```
30-12-2020 13:55:51
Version            : GH Injector V3.4
OS                 : Windows 10 Enterprise 1909 (Build 18363)
File               : (nullptr)
Target             : (undetermined)
Target PID         : 1220
Source             : Import Handler.cpp in ResolveImports at line 36
Errorcode          : 0x0000001C
Advanced errorcode : 0x00000000
Injectionmode      : LoadLibraryExW
Launchmethod       : NtCreateThreadEx
Platform           : ---
HandleValue        : 0x00000000
Flags              : 0x00000000
```

I have tried to use another injection mode and launchmethod but still no luck
below is my code 

```c++

	HINSTANCE hInjectionMod = LoadLibrary(GH_INJ_MOD_NAME);

	auto InjectA = (f_InjectA)GetProcAddress(hInjectionMod, "InjectA");

	INJECTIONDATAA data =
	{
		"C:\\Users\\Nanda Abi Fahmi\\source\\repos\\TestFunctionInjection\\TestFunctionInjection\\testdll.dll",
		PID,
		INJECTION_MODE::IM_LoadLibraryExW,
		LAUNCH_METHOD::LM_NtCreateThreadEx,
		NULL,
		0,
		NULL,
		0,
		true
	};

	InjectA(&data);
```

I am wondering if I'm missing something

Thanks

**Comment by ericchartier** [comment]
There's a std::future::wait_for(0) in Import Handler and Import Handler WOW64. It seems to be used as a trick to get the current status of the async function but it is possible that the function genuinely hasn't finished.

You can crank that to a higher number for this specific problem

**Comment by Broihon** [comment]
Use version 4.0 and use GetSymbolState to wait until the PDB download is finished and the imports are completed.

**Comment by Broihon** [comment]
@ericchartier yes, and it's not supposed to wait until the symbol parsing is done. That's why version 4.0 has an export which tells you whether symbol parsing is finished so that you can wait before calling any of the inject functions.
The symbol threads get launched in the dllmain of the library module(s) and if the pdb already exists (first run takes longer because of the download) it only takes a handful of milliseconds to verify the pdb and load the imports.

**Comment by nafalabi** [comment]
Thanks @Broihon 
I am able to inject my dll now
